file_direction: 'D:\Data Science for Life Science\Machine Learning and Deep learning\Data\Data_week3\pump_sensor_data'
file_name: 'sensor.csv'
output_path: 'D:/Python/data_programming_2/Week_2_7'
train_data: 'df_train.csv'