target_directory: 'D:\Python\data_programming_2\Week_2_7\target'
output_directory: 'D:\Python\data_programming_2\Week_2_7\output'
image_directory: 'D:\Python\data_programming_2\Week_2_7\output\images'
model_directory: 'D:\Python\data_programming_2\Week_2_7\model'
divided_data_directory: 'D:\Python\data_programming_2\Week_2_7\divided_data'
raw_file_directory: 'D:\Data Science for Life Science\Machine Learning and Deep learning\Data\Data_week3\pump_sensor_data'

sensor_names: ['sensor_04','sensor_12', 'sensor_00', 'sensor_02']
metric_names: ['precision', 'recall', 'f_score', 'confusion', 'accuracy', 'auc_roc']

